# Fly.io configuration for R10 Piauí Portal
app = "r10-piaui"
primary_region = "gru"

[build]

[env]
  NODE_ENV = "production"
  PORT = "8080"
  SERVE_STATIC_FRONT = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[mounts]]
  source = "r10_data"
  destination = "/data"
