services:
  - type: web
    name: r10piaui
    env: node
    runtime: node
    buildCommand: npm install && npm run build:render
    startCommand: node server/server-production.cjs
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: r10-data
      mountPath: /opt/render/project/src/data
      sizeGB: 5
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SERVE_STATIC_FRONT
        value: "1"
      - key: SQLITE_DB_PATH
        value: /opt/render/project/src/data/noticias.db
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: SEED_SECRET
        value: r10seed2025
    
    # ========================================================================
    # REGRAS DE ROTEAMENTO (A SOLUÇÃO PARA O PROBLEMA)
    # ========================================================================
    # O Render processa essas regras em ORDEM.
    # As primeiras regras têm prioridade sobre as últimas.
    # Isso garante que rotas específicas do servidor sejam processadas
    # ANTES da regra genérica do React SPA.
    # ========================================================================
    routes:
      # REGRA 1: Módulo de Arquivo (Notícias Antigas)
      # Permite que /arquivo/* passe direto para o servidor Express
      - type: rewrite
        source: /arquivo
        destination: /arquivo
      
      - type: rewrite
        source: /arquivo/*
        destination: /arquivo/:splat
      
      # REGRA 2: Rotas da API
      # Permite que /api/* passe direto para o servidor Express
      - type: rewrite
        source: /api/*
        destination: /api/:splat
      
      # REGRA 3: Uploads (imagens, arquivos)
      # Permite que /uploads/* passe direto para o servidor Express
      - type: rewrite
        source: /uploads/*
        destination: /uploads/:splat
      
      # REGRA 4: Áudios TTS (Text-to-Speech)
      # Permite que /tts/* passe direto para o servidor Express
      - type: rewrite
        source: /tts/*
        destination: /tts/:splat
      
      # REGRA 5 (FINAL): React SPA Fallback
      # Se nenhuma das regras acima corresponder, sirva o app React
      # Esta DEVE ser a última regra!
      - type: rewrite
        source: /*
        destination: /index.html
