services:
  - type: web
    name: r10piaui
    env: node
    runtime: node
    buildCommand: npm install && npm run build:render
    startCommand: node server/server-production.cjs
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: r10-data
      mountPath: /opt/render/project/src/data
      sizeGB: 5
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SERVE_STATIC_FRONT
        value: "1"
      - key: SQLITE_DB_PATH
        value: /opt/render/project/src/data/noticias.db
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: SEED_SECRET
        value: r10seed2025
    
    # ========================================================================
    # NOTA IMPORTANTE SOBRE ROTEAMENTO
    # ========================================================================
    # Para Web Services Node.js, as regras de rewrite são configuradas no
    # Dashboard do Render (Redirects/Rewrites) OU tratadas pelo próprio
    # servidor Express no server-production.cjs.
    # 
    # A seção 'routes' abaixo NÃO funciona para Web Services - ela é apenas
    # para Static Sites.
    # 
    # SOLUÇÃO: Remova a regra genérica /* -> /index.html do Dashboard do Render.
    # O server-production.cjs já cuida do roteamento corretamente.
    # ========================================================================
