name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install root deps
        run: npm install
      - name: Install frontend deps
        working-directory: r10-front_full_07ago
        run: npm install
      - name: Run tests (backend)
        run: npm test -- --runInBand
      - name: Coverage (backend)
        run: npm run test:coverage
      - name: Upload coverage summary
        if: always()
        run: |
          echo "Backend coverage:" >> $GITHUB_STEP_SUMMARY
          npm run test:coverage -- --coverageReporters=text-summary >> $GITHUB_STEP_SUMMARY || true
      - name: Frontend build check
        run: npm run build
      - name: Lint (placeholder)
        run: echo "No lint configured yet" 
